'use client'
import '../styles/globals.scss'
import AOS from 'aos'
import 'aos/dist/aos.css'
import { useEffect } from 'react'
import Header from '@/components/ui/header'
import Banner from '@/components/banner'
import Navbar from '../components/Navbar/Navbar'
// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-inter',
//   display: 'swap'
// })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    AOS.init({
      once: true,
      disable: 'phone',
      duration: 700,
      easing: 'ease-out-cubic',
    })
  })

  return (
    <html lang="en">
      <body className={` font-inter antialiased bg-white text-gray-900 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Navbar />
          {children}
          <Banner />
        </div>
      </body>
    </html>
  )
}
