'use client'
import '../styles/globals.css'
import AOS from 'aos'
import 'aos/dist/aos.css'



import { useEffect } from 'react'
import Footer from '@/components/ui/footer'
import Banner from '@/components/banner'
import Navbar from '../components/Navbar/Navbar'
import {Cloudinary} from '@cloudinary/url-gen'
import { NextUIProvider } from '@nextui-org/react'
import { ThemeProvider as NextThemesProvider } from "next-themes"


// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-inter',

//   display: 'swap'
// })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const cld = new Cloudinary({ cloud: { cloudName: 'drmonozsf' } });
export default function RootLayout({
 
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {

    AOS.init({
      once: true,
      disable: 'phone',
      duration: 700,
      easing: 'ease-out-cubic',
    })
  })

  return (
    <>
 
      <html lang="en  flex justify-center w-[100vw]">
        <body className={` relative  font-inter mx-auto max-w-[1920px] border border-red-500 outer-wrapper antialiased bg-white text-gray-900 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <div className="fix bg-neutral-800	 py-4 w-full text-white text-center ">
           我們讓試片長出了自己的電路系統
          </div>

            <NextUIProvider>
              <NextThemesProvider attribute="class" defaultTheme="dark">
                <Navbar />


                {children}

              </NextThemesProvider>
            </NextUIProvider>
          <Banner />
          <Footer/>
           
            
        </div>
      </body>
    </html>
    </>
  )
}
